// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARX_uk2gMMwvQUsaPHVNcfC2JqqFD9K2g',
    appId: '1:25234262896:web:51d3f86b3b098a883d5db5',
    messagingSenderId: '25234262896',
    projectId: 'directfarm-700b5',
    authDomain: 'directfarm-700b5.firebaseapp.com',
    storageBucket: 'directfarm-700b5.firebasestorage.app',
    measurementId: 'G-SR8MRG3TF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfSPnlFu3CFNCzA-0ce48WIpNfG7nl2mM',
    appId: '1:25234262896:android:fe03c4036efcb0cd3d5db5',
    messagingSenderId: '25234262896',
    projectId: 'directfarm-700b5',
    storageBucket: 'directfarm-700b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYillLiDA4kkFZ9hJzHFj8LTQ2dxHA7II',
    appId: '1:25234262896:ios:3254dc1d35cee4733d5db5',
    messagingSenderId: '25234262896',
    projectId: 'directfarm-700b5',
    storageBucket: 'directfarm-700b5.firebasestorage.app',
    iosBundleId: 'com.directfarm.app',
  );
}
